plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'db/migrate/**/*'
  - 'db/schema.rb'
  - 'vendor/**/*'

Layout/LineLength:
  Max: 160

Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/ClassMethodsDefinitions:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
