plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
  - 'bin/**/*'
  - 'db/migrate/**/*'
  - 'db/schema.rb'
  - 'vendor/**/*'

Layout/LineLength:
  Max: 160

Style/MethodCallWithArgsParentheses:
  Enabled: false

